before_install:
  - sudo add-apt-repository ppa:yjwong/opencv2 -y
  - sudo apt-get update -q

install: sudo apt-get -y install libopencv-dev libtesseract-dev git cmake build-essential libleptonica-dev liblog4cplus-dev libcurl3-dev beanstalkd

before_script:
  - mkdir -p ./src/build/
  - cd ./src/build/
  - cmake ..
script: 
  - make
  - make openalpr-utils-classifychars openalpr-utils-tagplates openalpr-utils-benchmark openalpr-utils-prepcharsfortraining
  - sudo make install
  - ./tests/unittests



